name: backend-website

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install -r ./requirements.txt 
      - run: pdoc -d google backend/ -o ./backend/docs
      - uses: actions/upload-artifact@v3
        with:
          name: backend-docs
          path: ./backend/docs/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-docs
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: backend-docs
          path: backend-docs
      - run: ls -la # Listar arquivos para verificar se o artefato foi baixado corretamente
      - run: |
          mkdir -p backend
          cp -r backend-docs/* backend/
      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add backend/
          git commit -m "Update backend documentation"
          git pull --rebase origin gh-pages --allow-unrelated-histories
          git push origin gh-pages