name: website
# build the documentation whenever there are new commits on main
on:
  push:
    branches:
      - main
    # Alternative: only build for tags.
    # tags:
    #   - '*'
# security: restrict permissions for CI jobs.
permissions:
  contents: read
jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      # Install all dependencies (including pdoc)
      - run: pip install -r backend/requirements.txt 
      # Build your backend documentation into docs/backend/
      - run: pdoc -d google backend/ -o ./docs/backend
      # Install frontend dependencies
      - run: |
          cd frontend
          npm install
      # Build your frontend documentation into frontend/docs/
      - run: |
          cd frontend
          npm run docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: |
            docs/backend
            frontend/docs
  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4