name: frontend-website

on:
  push:
    branches:
      - main 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: |
          cd frontend
          npm install
      - run: |
          cd frontend
          npm run docs
      - uses: actions/upload-artifact@v3
        with:
          name: frontend-docs
          path: frontend/docs/
              
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: deploy-docs
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 0
      - uses: actions/download-artifact@v3
        with:
          name: frontend-docs
          path: frontend-docs
      - run: ls -la 
      - run: |
          mkdir -p frontend
          cp -r frontend-docs/* frontend/
      - run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add frontend/
          git commit -m "Update frontend documentation"
          git pull --rebase origin gh-pages --allow-unrelated-histories
          git push origin gh-pages