name: frontend-website
# Build the documentation whenever there are new commits on the frontend branch
on:
  push:
    branches:
      - frontend # Define que esse workflow só roda para commits na branch frontend

# Security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      # Install frontend dependencies
      - run: |
          cd frontend
          npm install
      # Build your frontend documentation into frontend/docs/
      - run: |
          cd frontend
          npm run docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/docs/
          
  # Deploy the artifact to GitHub pages.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
        with:
          # Publish to the gh-pages branch of the frontend branch
          branch: frontend # Indica que o deploy será feito para a branch frontend
